const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const ADD_SOME = 'ADD_SOME';

const ADD_PERSON = 'ADD_PERSON';
const DELETE_PERSON = 'DELETE_PERSON';

export { INCREMENT, DECREMENT, ADD_SOME };
export { ADD_PERSON, DELETE_PERSON };
